title:              Test for a clean easy web.
email:              exampleemail@email.com
description:        This is a test for a site.
author:             Marcos
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://apa-marcos.github.io"

# Social Profiles
twitter_username:   Marcos
github_username:    Marcos
facebook_username:  Marcos
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
